[general]
live_config_reload = true
# Source: https://github.com/tinted-theming/tinted-terminal/blob/main/themes/alacritty/base16-onedark.toml
import = ["./base16-onedark.toml"]

[window]
padding = { x = 2, y = 2 }
dynamic_padding = true
decorations_theme_variant = "Dark"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
offset = { x = 0, y = 1 }

[cursor]
style = { shape = "Beam", blinking = "On" }
thickness = 0.2

[mouse]
bindings = [
{ mouse = "Right", action = "Copy" },
]
