[general]
live_config_reload = true

[window]
padding = { x = 2, y = 2 }
dynamic_padding = true
decorations_theme_variant = "Dark"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
offset = { x = 0, y = 1 }

[cursor]
style = { shape = "Beam", blinking = "On" }
thickness = 0.2

[mouse]
bindings = [
{ mouse = "Right", action = "Copy" },
]


################################################################################
# Source: https://github.com/alacritty/alacritty-theme/blob/master/themes/one_dark.toml

# Colors (One Dark)

# Default colors
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
