
" Get the defaults.
source $VIMRUNTIME/defaults.vim

" Set compatibility to Vim only
set nocompatible
set encoding=utf-8



" Line numbers
set number relativenumber
set numberwidth=5

" Enable mouse usage
set mouse=a

" Syntax highlighting
filetype plugin on
syntax on

" Indentation
filetype indent on

" Highlighting search results
set incsearch
set hlsearch

" Colorscheme
set termguicolors  " Only needed for terminal vim
colorscheme base16-onedark

" Show whitespace characters
set list
set listchars=tab:→\ ,trail:·,extends:>,precedes:<,multispace:·


set autochdir
set autoindent
set smartindent

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


" Cursor settings
let &t_SI .= "\e[5 q"
let &t_SR .= "\e[1 q"
let &t_EI .= "\e[1 q"
" https://superuser.com/questions/431233/vim-shortcut-to-move-to-beginning-of-next-line-end-of-previous-line
set whichwrap+=<,>,h,l,[,]


" Statusline
" https://stackoverflow.com/questions/5375240/a-more-useful-statusline-in-vim
set statusline=[%n] "buffernr
set statusline+=\ %F%m%r%h%w
set statusline+=%=
set statusline+=\ Ln:%l/%L\ Col:%c
set statusline+=\ %y "file type
